sudo: required

services:
    - docker

before_install:
    - docker pull matthewsedam/chapel:latest

script: ./dockerBuild.sh && echo && ./dockerBuild.sh test && echo 
        && ./build/test/cryptotradetest
