language: python
python:
  - "3.6"

install:
  - pip install pytest-cov codecov flake8
  - pip install -r requirements.txt
  - python setup.py develop

before_script:
  - flake8 .

script:
  - py.test --cov=./
  - codecov
