sudo: required

services:
    - docker

before_install:
    - docker pull matthewsedam/chapel:latest

script: ./dockerBuild.sh && echo && chmod +x ./src/test/start_tests.sh
       && chmod +x ./src/test/processTest.sh && ./dockerBuild.sh test
