sudo: required
language: generic

services:
    - docker

before_install:
    - docker pull matthewsedam/chapel:latest

before_script:
    - chmod +x ./src/test/start_tests.sh
    - chmod +x ./src/test/processTest.sh

script:
    - ./dockerBuild.sh
    - ./dockerBuild.sh test
